### ISSUE TITLE
About g4ad AMD GPU's

### ISSUE THREAD

**Issue by Shubuo** [mludvig/aws-ethereum-miner#26] opened 2021-12-15 13:26 UTC
Has anyone tried it and got it working? I tried to run the machine with the previous methods, but I was not successful with NBMiner and T-rex miners, I get the "no GPU detected" problem, I think the problem is caused by CUDA, still couldn't find a solution.  
I suppose that it will be more cost efficient but also curious about how much return they will provide. 
Do you have any experience about that new GPU instances ?

**Comment by mludvig** [comment] 2021-12-15 21:48
Duplicate of #25 

The trouble is that Radeons need a completely different software stack - both the OS drivers and the miner, since they are not CUDA compatible. I tried to make it work some time ago and didn't quite succeed. One day I may have a look at it again.

**Closed** 2021-12-15 21:49 UTC

**Comment by jxu** [comment] 2022-01-05 11:59
Is this instance type working now given that it's in https://medium.com/coinmonks/new-aws-instance-that-makes-eth-mining-profitable-1dd87183cce7? I got error "No OpenCL platforms found" with ethminer 0.19.0 on Deep Learning AMI (Ubuntu 18.04) Version 54.0 - ami-0476bba883df7cca6.

**Comment by mludvig** [comment] 2022-01-23 22:18
@jxu I don't use Deep Learning AMI - it's too big (100GB) and that storage cost adds up when you run a lot of miners. Best to use the template provided, it's a verified and optimised combination of lightweight AMI and a compatible ethminer.

**Comment by jxu** [comment] 2022-01-24 11:10
Thanks for letting me know. I got your templates working and managed to burn through some leftover AWS credits. The only issue now is that with ethermine pool, the payout gas fees on mainnet are very high and otherwise the payout is on Layer 2 Polygon network as wETH. But that has nothing to do with your excellent templates.

**Comment by jxu** [comment] 2022-01-24 23:20
Yes, gas prices have come down (it was like at 160 gwei before due to the stupid sunflower game). I chose to put my wETH on Polygon but now it'll have to be bridged across to mainnet if I want it there.

Do you have an article on bridging? The ones I know of are Hop, Polygon, and now Umbria. Umbria promises a fee of only 0.0037 eth to bridge but I have not tested them yet (also idk if I require tokens in any other currency).

**Comment by mludvig** [comment] 2022-01-24 23:37
I have don't have much in WETH and what I have I use for playing with DeFi. For example deposited some WETH on AAVE to earn a bit of interest and some MATIC on top. Just be careful out there, DeFi is a wild west...

**Comment by jxu** [comment] 2022-01-24 23:43
Do you use the same address for weth? I can tip you for the nice blog posts you've made :) (depending on how much transfer fees within Polygon are)

**Comment by mludvig** [comment] 2022-01-24 23:49
Yes the same one 0x99b... that's in the README - you kinda have to use the same because with ethermine you mine to an address and only then choose if you want a payout over mainnet or over polygon, and can switch between them, so the addr is the same in both cases.

**Comment by jxu** [comment] 2022-01-25 00:55
Ok. To send within Polygon, it requires MATIC, but it also requires MATIC to swap wETH for MATIC... I think the process of adding MATIC itself requires an exchange on mainnet so it's expensive? There's also apparently MATIC faucets (https://matic.supply/) that just give away a little for free? You're right, this stuff is insane. I have to go by word of mouth on what is legit or not. https://www.reddit.com/r/maticnetwork/comments/nsp52a/this_is_how_you_get_matic_to_the_metamask_wallet/ 

Sorry for cluttering this issue page. Maybe this discussion can be moved somewhere (I think github has discussions feature now.)

**Comment by mludvig** [comment] 2022-01-25 08:15
Yeah it’s a chicken and egg problem. I used a faucet the first time I started with Polygon, it gave me a few cents worth of Matic to start with for free.

**Comment by mludvig** [comment] 2022-01-25 21:08
@jxu Thanks for the tip, much appreciated :)

**Comment by jxu** [comment] 2022-01-26 12:44
You're welcome. Tho eth has dropped in value a lot due to network congestion and high gas fees, so maybe the few tokens I sent will be worth less and less in the near future
